const ORDER_STATUS_FLOW = {
  NEW: ["CONFIRMED", "CANCELED"],
  CONFIRMED: ["PROCESSING", "CANCELED"],
  PROCESSING: ["COMPLETED", "CANCELED"],
  COMPLETED: [],
  CANCELED: [],
};

module.exports = { ORDER_STATUS_FLOW };
